### ISSUE TITLE
chocochino

### ISSUE THREAD

**Issue by llohanda** [BesutKode/uni-task-1#15]
https://github.com/BesutKode/uni-task-1/wiki/chocochino

**Comment by jayvdb** [comment]
https://github.com/webcamoid/webcamoid/commit/18cd05ff8505362 : 1 fix
https://github.com/webcamoid/webcamoid/commit/d5c461e49f8673a : 1 fix (I am not 100% confident about the removal of the ` `, but I will accept it)
https://github.com/webcamoid/webcamoid/commit/f9cdba1ab29cb01b : 1 fix
https://github.com/webcamoid/webcamoid/commit/a658d9424bdc38d9d : 3 fixes (I am not 100% confident about the removal of the` `, but I will accept it)
https://github.com/webcamoid/webcamoid/commit/679ecac3d4e8766e4 : probably incorrect fix ;`ID Plugin`is a reasonable translation of`Plugin id`.  This type of change should only be done by an Italian language expert.

https://github.com/Kestutis-Z/World-Weather/commit/308171c3e765478 : 1 fix

Unmerged changes to https://hosted.weblate.org/projects/openorienteering/mapper/id/ by https://hosted.weblate.org/user/chocochino/ : 20+ :+1:

https://github.com/chocochino/PeriksaJamak :+1:
