### ISSUE TITLE
AmdHamdani

### ISSUE THREAD

**Issue by noodle-eater** [BesutKode/uni-task-1#18]
<https://github.com/BesutKode/uni-task-1/wiki/AmdHamdani>

**Comment by jayvdb** [comment]
`{feature-that-broke}: {what-went-wrong}`

These are not variables. They are supposed to be translated.

`{{last_modified_time}`

This is a real bug. :+1: 1 bug detected.

```
E201: invalid variables: %-o
1554:#: ../gui/filehandling.py:113
1555:msgid "JPEG 90% quality (*.jpg; *.jpeg)"
1556:msgstr "JPEG 90%-os minőség (*.jpg; *.jpeg)"
```

Not correct.  The '%' there is not a variable; it is a percent sign.

```
E201: invalid variables: {podpowiedź}
3172:#: ../po/tmp/brusheditor.glade.h:48
3173:msgid "{tooltip}"
3174:msgstr "{podpowiedź}"
```

I am relatively confident this is a bug:

```
$ git grep --after-context=1 '{tooltip}' | grep msgstr | grep -v '""' | egrep -v '{tooltip}'
po/pl.po-msgstr "{podpowiedź}"
```

Github Repository : Tiled :+1:  1 bug detected.

Github Repository : Cyanide (Different capitalization in German translations) :-1:  Please revert your changes to these message on this repository ( https://hosted.weblate.org/changes/?user=amdhamdani )

Total so far: 2 bugs detected

"Find one more bug" part of this task is also not done.

**Comment by noodle-eater** [comment]
Ok sir

**Comment by jayvdb** [comment]
In `plinth/locale/id/LC_MESSAGES/django.po` you did [this change](https://github.com/freedombox/Plinth/commit/552dcb31dcdd4):

```diff
@@ -308,8 +310,9 @@ msgid "Result"
 msgstr "Hasil"
 
 #: plinth/modules/disks/__init__.py:35 plinth/modules/disks/views.py:39
+#: plinth/modules/disks/__init__.py:35,
 msgid "Disks"
-msgstr "Diska"
+msgstr "Disk"
 
 #: plinth/modules/disks/templates/disks.html:35
 msgid "The following disks are in use:"
```

'Diska' is not in kbbi; but 'Disk' is also not in kbbi.  Is there a better word for this?

**Comment by berviantoleo** [comment]
In KBBI IV, Diska available, but Disk not. Refer to this : http://kbbi4.portalbahasa.com/entri/diska

**Comment by laymonage** [comment]
FYI, KBBI V launched on 28 October 2016. Here's the entry for diska: http://kbbi.kemdikbud.go.id/entri/diska

**Comment by noodle-eater** [comment]
Ok done. Thanks for the infomation very useful.
