### ISSUE TITLE
Prasastoadi

### ISSUE THREAD

**Issue by prasastoadi** [BesutKode/uni-task-1#19]
https://github.com/BesutKode/uni-task-1/wiki/prasastoadi

The last 5 bugs have not been merged.

**Comment by prasastoadi** [comment]
https://github.com/gammu/gammu/commit/7737ed8ffeadc936547e72c8a62fd164b432a033
Merged

**Comment by jayvdb** [comment]
https://github.com/yast/yast-translations/commits?author=prasastoadi = 8 :+1:

https://github.com/ximion/appstream/commit/037664add0f9c63d6c = 2

https://github.com/freeplane/freeplane/commit/f81bcf83058e59c1d = 2

https://github.com/openSUSE/zypper/commit/cd542161cb0a66d = 8

https://github.com/gammu/gammu/commit/7737ed8ffeadc936547e = 5

https://github.com/prasastoadi/serangkai :+1:
