### ISSUE TITLE
taufiqsumadi

### ISSUE THREAD

**Issue by taufiqsumadi** [BesutKode/uni-task-1#21]
https://github.com/BesutKode/uni-task-1/wiki/taufiqsumadi

@jayvdb

**Comment by jayvdb** [comment]
https://github.com/bil-elmoussaoui/Gnome-TwoFactorAuth/pull/19 👍 9

https://github.com/liberapay/liberapay.com/pull/426 :+1: 1

https://github.com/liberapay/liberapay.com/commit/bd636dc7525a22e90a7cae7ee :+1: 10
([and more](https://github.com/liberapay/liberapay.com/commits?author=taufiqsumadi))

https://github.com/taufiqsumadi/CekKataFormal -- hmmm, this is very similar to [existing tools](https://github.com/BesutKode/uni-task-1/wiki/Existing-tools), but nobody else's tool appears to recommend `Saya` for `atu`, so :+1: .

**Comment by jayvdb** [comment]
Please submit a PR to add a ✔️  to https://besutkode.github.io/

**Comment by ghost** [comment]
In this PR (https://github.com/bil-elmoussaoui/Gnome-TwoFactorAuth/pull/19/files), there are two mistakes made about the spacing before colon. Please fix it.

Ref: http://french.about.com/od/grammar/fl/How-to-Use-French-Punctuation.htm

**Comment by jayvdb** [comment]
Thx for spotting that @edawine .

@taufiqsumadi ,
You have more than 20 good fixes, so, you are still passing.
But we cant reduce quality of translations, so please fix those two in weblate, and then we can close this again.

**Comment by taufiqsumadi** [comment]
https://hosted.weblate.org/translate/gnome-twofactorauth/translation/fr/?sid=9e032770-b86c-11e6-a638-5254000d9bae&offset=35 and https://hosted.weblate.org/translate/gnome-twofactorauth/translation/fr/?sid=9e032770-b86c-11e6-a638-5254000d9bae&offset=36 done fix translation @jayvdb 

thx @edawine

**Comment by jayvdb** [comment]
I do not see them in the history: https://hosted.weblate.org/projects/gnome-twofactorauth/translation/fr/#history

**Comment by jayvdb** [comment]
I've left a note at https://github.com/bil-elmoussaoui/Gnome-TwoFactorAuth/pull/19#discussion-diff-85633013R179
