### ISSUE TITLE
Lidilidian

### ISSUE THREAD

**Issue by Lidilidian** [BesutKode/uni-task-1#5]
https://github.com/BesutKode/uni-task-1/wiki/Lidilidian

**Comment by arkrwn** [comment]
> However, I do not see your new tools needed for the "Find one more bug" / '"Temukan satu lagi bug".

working on it.

**Comment by arkrwn** [comment]
https://github.com/BesutKode/uni-task-1/wiki/Lidilidian

please check my "Find one more bug" tools mr @jayvdb , Thanks :+1:

**Comment by jayvdb** [comment]
https://github.com/Lidilidian/Transarietmator is absolutely awesome, but it does not meet the criteria _yet_.

The task is to detect bugs in translations.  A missing translation is not a bug, but more importantly there are many tools that already detect that the translation is missing.

Furthermore, _if_ any of your programs suggested translations were added to an Open Source repository, that repository is now legally required to attribute Microsoft, including display the Microsoft Logo.  See https://www.microsoft.com/en-us/translator/faq.aspx and https://www.microsoft.com/en-us/translator/attribution.aspx .

However, your effort is not wasted.

To turn your application into a tool which meets the criteria, add a mode that looks at translated messages, and compare the existing human translation with the Microsoft Automated Translation.  In your comparison, look for messages where the existing human translation and the Microsoft translations are significantly different; so different that your tool believes the human translation is _wrong_.

Do **NOT** print out the Microsoft Translation - if the human reads it, and uses it, the Open Source software has been infected by Microsoft and is no longer open source.

**Comment by arkrwn** [comment]
is this oke https://github.com/Lidilidian/Transarietmator ? mr @jayvdb

**Comment by jayvdb** [comment]
Done.
